# Generated by Django 3.0.7 on 2021-05-10 09:45

from django.db import migrations, models
import django.utils.timezone
from django.conf import settings
from restaurateur.geo import fetch_coordinates


def fill_coordinates(apps, shema_editor):
    addresses = []
    CoordinatesAddresses = apps.get_model('addressclassifier', 'CoordinatesAddresses')
    Restaurant = apps.get_model('foodcartapp', 'Restaurant')
    Order = apps.get_model('foodcartapp', 'Order')
    addresses.extend(Restaurant.objects.values_list('address', flat=True))
    addresses.extend(Order.objects.values_list('address', flat=True))
    for address in addresses:
        lng, lat = fetch_coordinates(settings.YANDEX_API_KEY, address)
        CoordinatesAddresses.objects.get_or_create(
            address=address,
            lng=lng, lat=lat
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatesAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Координаты адресов',
                'verbose_name_plural': 'Координаты адресов',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(fill_coordinates),
    ]
