# Generated by Django 3.0.7 on 2021-03-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20210327_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('raw', 'Необработанный'), ('processed', 'Обработанный')], default='raw', max_length=10, verbose_name='статус обработки'),
        ),
    ]
