# Generated by Django 3.0.7 on 2021-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='комментарий'),
        ),
    ]
