# Generated by Django 3.0.7 on 2021-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20210328_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные, при получении'), ('online', 'Предоплата онлайн')], default='cash', max_length=10, verbose_name='Форма оплаты'),
        ),
    ]
