# Generated by Django 3.0.7 on 2021-03-29 11:27
import django.db.models.deletion
from django.db import migrations, models
from collections import Counter
from more_itertools import first


def allocate_restaurants_on_order(order, products, restaurants):
    products_in_order = [item['product'] for item in products if item['order'] == order.id]
    restaurants_by_order = Counter(
        (
            items['restaurant__id']
        ) for items in restaurants if items['product'] in products_in_order
    )
    return list(
        first(item) for item in restaurants_by_order.most_common(len(products_in_order))
    )


def fill_restorans_in_orders(apps, shema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    Restaurant = apps.get_model('foodcartapp', 'Restaurant')
    ProductsOrdered = apps.get_model('foodcartapp', 'ProductsOrdered')
    RestaurantMenuItem = apps.get_model('foodcartapp', 'RestaurantMenuItem')

    orders = Order.objects.all()
    products = ProductsOrdered.objects.filter(order__in=orders).values('order', 'product')
    restaurants = RestaurantMenuItem.objects.filter(
        availability=True, product__in=products.values('product')
    ).values('id', 'product')

    for order in orders:
        restaurant = first(allocate_restaurants_on_order(order, products, restaurants))
        order.restaurant = Restaurant.objects.get(id=restaurant['restaurant__id'])

    Order.objects.bulk_update(orders, ['restaurant'])


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oders', to='foodcartapp.Restaurant', verbose_name='ресторан', null=True),
            preserve_default=False,
        ),
        migrations.RunPython(fill_restorans_in_orders),
    ]
