# Generated by Django 3.0.7 on 2021-03-29 11:27
import django.db.models.deletion
from more_itertools import first
from django.db import migrations, models
from foodcartapp.models import Restaurant, Order


def fill_restorans_in_orders(apps, shema_editor):
    orders = Order.objects.all()
    for order in orders:
        restaurant = first(Order.objects.filter(id=order.id).fetch_restaurants())
        order.restaurant = Restaurant.objects.get(name=restaurant['restaurant__name'])
    Order.objects.bulk_update(orders, ['restaurant'])


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oders', to='foodcartapp.Restaurant', verbose_name='ресторан', null=True),
            preserve_default=False,
        ),
        migrations.RunPython(fill_restorans_in_orders),
    ]
