# Generated by Django 3.0.7 on 2021-03-29 11:27
import django.db.models.deletion
from django.db import migrations, models
from collections import Counter
from more_itertools import first


def fill_restaurant_in_orders(apps, shema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    Restaurant = apps.get_model('foodcartapp', 'Restaurant')
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    RestaurantMenuItem = apps.get_model('foodcartapp', 'RestaurantMenuItem')

    orders = Order.objects.all()
    for order in orders:

        count_ordered_products_in_restaurants = Counter(
            items.restaurant.id for items in RestaurantMenuItem.objects.filter(
                availability=True,
                product__in=OrderItem.objects.filter(order=order).values('product')
            )
        )
        most_suitable_restaurants = list(map(
            lambda item: item[0], count_ordered_products_in_restaurants.most_common(1)
        ))

        if not most_suitable_restaurants:
            continue

        order.restaurant = Restaurant.objects.get(id=first(most_suitable_restaurants))

    Order.objects.bulk_update(orders, ['restaurant'])


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='oders',
                to='foodcartapp.Restaurant',
                verbose_name='ресторан',
                null=True
            ),
            preserve_default=False,
        ),
        migrations.RunPython(fill_restaurant_in_orders),
    ]
