# Generated by Django 3.0.7 on 2021-03-31 16:20
from django.db import migrations, models
from django.conf import settings
from restaurateur.geo import fetch_coordinates


def fill_coordinates(apps, shema_editor):
    addresses = []
    CoordinatesAddresses = apps.get_model('foodcartapp', 'CoordinatesAddresses')
    Restaurant = apps.get_model('foodcartapp', 'Restaurant')
    Order = apps.get_model('foodcartapp', 'Order')
    addresses.extend(Restaurant.objects.values_list('address', flat=True))
    addresses.extend(Order.objects.values_list('address', flat=True))
    for address in addresses:
        lng, lat = fetch_coordinates(settings.YANDEX_API_KEY, address)
        CoordinatesAddresses.objects.get_or_create(
            address=address,
            lng=lng, lat=lat
        )


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatesAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('lng', models.FloatField(blank=True, default=0.0, verbose_name='Долгота')),
                ('lat', models.FloatField(blank=True, default=0.0, verbose_name='Широта')),
            ],
        ),
        migrations.RunPython(fill_coordinates),
    ]
