# Generated by Django 3.0.7 on 2021-03-31 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20210331_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatesaddresses',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
    ]
