# Generated by Django 3.0.7 on 2021-05-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_coordinatesaddresses_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinatesaddresses',
            options={'ordering': ['id'], 'verbose_name': 'Координаты адресов', 'verbose_name_plural': 'Координаты адресов'},
        ),
        migrations.AlterField(
            model_name='coordinatesaddresses',
            name='lat',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coordinatesaddresses',
            name='lng',
            field=models.FloatField(default=0.0, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.Restaurant', verbose_name='ресторан'),
        ),
    ]
