# Generated by Django 3.0.7 on 2021-05-10 07:59

from django.db import migrations, models


def remove_coordinates(apps, shema_editor):
    CoordinatesAddresses = apps.get_model('foodcartapp', 'CoordinatesAddresses')
    CoordinatesAddresses.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20210510_0204'),
    ]

    operations = [
        migrations.RunPython(remove_coordinates),
        migrations.AlterField(
            model_name='coordinatesaddresses',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='адрес'),
        ),
    ]
