# Generated by Django 3.0.7 on 2021-05-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20210510_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoordinatesAddresses',
        ),
    ]
