# Generated by Django 3.0.7 on 2021-12-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_auto_20210809_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные, при получении'), ('online', 'Предоплата онлайн')], db_index=True, default='cash', max_length=10, verbose_name='Форма оплаты'),
            preserve_default=False,
        ),
    ]
